onlyBuiltDependencies:
  - '@nestjs/core'
  - '@scarf/scarf'
  - bcrypt

overrides:
  "handlebars@>=4.0.0 <4.7.9": "4.7.9"
  "minimatch@>=9.0.0 <9.0.7": "9.0.7"
  "path-to-regexp@>=8.0.0 <8.4.0": "8.4.0"
  "picomatch@<2.3.2": "2.3.2"
  "picomatch@>=4.0.0 <4.0.4": "4.0.4"
