import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import {
  IsDateString,
  IsOptional,
  IsString,
  IsUUID,
  MinLength,
} from 'class-validator';

export class AgentHeartbeatDto {
  @ApiProperty({
    format: 'uuid',
    example: 'b7f88611-b63e-4c95-9f37-4afb5c0cf275',
    description: 'Node identifier returned during registration.',
  })
  @IsUUID()
  nodeId: string;

  @ApiProperty({
    example: '8eb84760b145bd1805e87ef4c0947b7b142d1bed3428f70f9b5f6f0a11baeb42',
    minLength: 32,
    description: 'Agent token returned during registration.',
  })
  @IsString()
  @MinLength(32)
  agentToken: string;

  @ApiPropertyOptional({
    example: '1.2.3',
    description:
      'Optional agent version reported with the heartbeat for observability.',
  })
  @IsOptional()
  @IsString()
  @MinLength(1)
  agentVersion?: string;

  @ApiPropertyOptional({
    example: '24.04',
    description:
      'Optional host platform version reported with the heartbeat for fleet observability.',
  })
  @IsOptional()
  @IsString()
  @MinLength(1)
  platformVersion?: string;

  @ApiPropertyOptional({
    example: '6.8.0',
    description:
      'Optional host kernel version reported with the heartbeat for fleet observability.',
  })
  @IsOptional()
  @IsString()
  @MinLength(1)
  kernelVersion?: string;

  @ApiPropertyOptional({
    format: 'date-time',
    example: '2026-03-18T10:15:00.000Z',
    description:
      'Optional timestamp generated by the agent when the heartbeat was sent.',
  })
  @IsOptional()
  @IsDateString()
  sentAt?: string;
}
