export const SYSTEM_EVENT_TYPES = {
  AGENT_UPDATE_ROLLOUT_CREATED: 'agent.update.rollout.created',
  AGENT_UPDATE_TARGET_COMPLETED: 'agent.update.target.completed',
  AGENT_UPDATE_TARGET_DISPATCHED: 'agent.update.target.dispatched',
  AGENT_UPDATE_TARGET_FAILED: 'agent.update.target.failed',
  HIGH_CPU: 'high.cpu',
  NODE_NOTIFICATIONS_UPDATED: 'node.notifications.updated',
  NODE_ROOT_ACCESS_UPDATED: 'node.root-access.updated',
  NODE_OFFLINE: 'node.offline',
  NODE_ONLINE: 'node.online',
  NODE_REGISTERED: 'node.registered',
  TASK_CANCELLED: 'task.cancelled',
  TASK_COMPLETED: 'task.completed',
  TASK_FAILED: 'task.failed',
  TASK_QUEUED: 'task.queued',
  TASK_SCHEDULE_CREATED: 'task.schedule.created',
  TASK_SCHEDULE_UPDATED: 'task.schedule.updated',
  TASK_SCHEDULE_DELETED: 'task.schedule.deleted',
  TASK_SCHEDULE_TRIGGERED: 'task.schedule.triggered',
  TASK_SCHEDULE_FAILED: 'task.schedule.failed',
  TASK_STARTED: 'task.started',
} as const;
