export const SYSTEM_EVENT_TYPES = {
  HIGH_CPU: 'high.cpu',
  NODE_OFFLINE: 'node.offline',
  NODE_ONLINE: 'node.online',
  NODE_REGISTERED: 'node.registered',
  TASK_CANCELLED: 'task.cancelled',
  TASK_COMPLETED: 'task.completed',
  TASK_FAILED: 'task.failed',
  TASK_QUEUED: 'task.queued',
  TASK_SCHEDULE_CREATED: 'task.schedule.created',
  TASK_SCHEDULE_UPDATED: 'task.schedule.updated',
  TASK_SCHEDULE_DELETED: 'task.schedule.deleted',
  TASK_SCHEDULE_TRIGGERED: 'task.schedule.triggered',
  TASK_SCHEDULE_FAILED: 'task.schedule.failed',
  TASK_STARTED: 'task.started',
} as const;
